# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

staging:
  adapter: postgresql
  database: fsl_staging
  encoding: unicode
  host: localhost
  username: JKereakoglow
  password:
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
